name: E2E / TEST Smoke2

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  kind-cri-smoke:
    uses: ./.github/workflows/e2e-kind-cri-smoke.yml
    with:
      memagent_ref: main
    secrets: inherit
  compose-redis:
    uses: ./.github/workflows/e2e-compose-redis.yml
    with:
      memagent_ref: main
    secrets: inherit
